### ISSUE TITLE
drive_ls don't works 

### ISSUE THREAD

**Issue by RafaelFNovi** [tidyverse/googledrive#404] opened 2022-11-22 23:14 UTC
drive_ls("~/Shared with me/folder1/folder2")

Error in `as_parent()`:
! Parent specified via `path` is invalid:
x Does not exist.
Run `rlang::last_error()` to see where the error occurred.

**Comment by jennybc** [comment] 2022-11-22 23:23
Presumably a duplicate of #396

**Comment by RafaelFNovi** [comment] 2022-11-22 23:45
Hi Jenny, thank you!
I used this and works :)
 drive_ls(as_id("id of my folder"))

**Closed** 2022-11-23 06:16 UTC
