### ISSUE TITLE
drive_auth() issue that I haven't seen yet

### ISSUE THREAD

**Issue by claytonperry** [tidyverse/googledrive#335] opened 2021-04-19 00:44 UTC
Hey all. I've seen similar issues to the one that I'm experiencing with googledrive and googlesheets4 but haven't come across an issue report here or on stackoverflow that quite helps.

One day, suddenly my drive_auth() and all other googledrive | googlesheets4 commands started giving me this response:

`Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html`

For example, simple code like this will yield that response above:

`library(googledrive)

drive_auth()`

I've seen folks use the command 

`options(gargle_verbosity = 'debug')`

to get more information about the issue. When I do that, it yields this output:

`> trying `token_fetch()`
> trying `credentials_service_account()`
> Error caught by `token_fetch()`:
  Argument 'txt' must be a JSON string, URL or file.
> trying `credentials_app_default()`
> trying `credentials_gce()`
> trying `credentials_byo_oauth()`
> Error caught by `token_fetch()`:
  inherits(token, "Token2.0") is not TRUE
> trying `credentials_user_oauth2()`
> Gargle2.0 initialize
> attempt to access internal gargle data from: googledrive
> adding userinfo.email scope
> Error caught by `token_fetch()`:
  error reading from connection`

I really appreciate any guidance you all could provide!! My apologies if the formatting in this post is not great - this is the first time I've submitted an issue.

**Comment by jennybc** [comment] 2021-04-19 16:15
This doesn't look familiar to me:

```
Error caught by token_fetch():
error reading from connection`
```

You say you've seen it reported elsewhere?

---

Zooming back out, this could have something to do with recent updates to gargle (which _should_ work with CRAN googledrive, but maybe you've found a bug?) or with old/non-refreshable tokens. It's hard to say.

What versions of googledrive and gargle do you have?

What does `gargle::gargle_oauth_sitrep()` show?

**Comment by claytonperry** [comment] 2021-04-19 17:53
Hi Jenny! I apologize for the miscommunication - what I meant is that I have seen folks getting this error message before:

`Error: Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:

drive_deauth() to prevent the attempt to get credentials.
Call drive_auth() directly with all necessary specifics.
Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html`

but I have not yet seen an issue including the language in the gargle_verbosity = 'debug' output that you picked out above.

------------
Here's my sessionInfo() output, indicating the versions of googledrive and gargle that are installed:
------------
other attached packages:
 [1] googlesheets4_0.3.0 forcats_0.5.1       stringr_1.4.0       dplyr_1.0.5         purrr_0.3.4        
 [6] readr_1.4.0         tidyr_1.1.3         tibble_3.1.0        ggplot2_3.3.3       tidyverse_1.3.1    
[11] **googledrive_1.0.1**  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6       cellranger_1.1.0 pillar_1.6.0     compiler_4.0.5   dbplyr_2.1.1     tools_4.0.5     
 [7] lubridate_1.7.10 jsonlite_1.7.2   lifecycle_1.0.0  **gargle_1.1.0**     gtable_0.3.0     pkgconfig_2.0.3 
[13] rlang_0.4.10     reprex_2.0.0     cli_2.4.0        DBI_1.1.1        rstudioapi_0.13  curl_4.3        
[19] haven_2.3.1      xml2_1.3.2       withr_2.4.1      httr_1.4.2       hms_1.0.0        generics_0.1.0  
[25] fs_1.5.0         vctrs_0.3.6      rappdirs_0.3.3   grid_4.0.5       tidyselect_1.1.0 glue_1.4.2      
[31] R6_2.5.0         fansi_0.4.2      readxl_1.3.1     modelr_0.1.8     magrittr_2.0.1   backports_1.2.1 
[37] scales_1.1.1     ellipsis_0.3.1   rvest_1.0.0      assertthat_0.2.1 colorspace_2.0-0 utf8_1.1.4      
[43] stringi_1.5.3    munsell_0.5.0    broom_0.7.6      crayon_1.4.1    
------------

Taking your suggestion, when I run `gargle::gargle_oauth_sitrep()` I receive the message below:

"No gargle OAuth cache found at C:/Users/perry/AppData/Local/gargle/gargle/Cache"

**Comment by jennybc** [comment] 2021-04-19 19:16
Are you doing anything to set gargle options or are you accepting all of the defaults?

**Comment by claytonperry** [comment] 2021-04-20 13:42
I have not been setting any gargle options so I believe it should be running on all defaults.

I have been working in RStudio - I'm not sure how I would test this in an interactive session, I do not know how to switch between an interactive and non-interactive session.

**Comment by jennybc** [comment] 2021-04-20 15:31
> I have been working in RStudio - I'm not sure how I would test this in an interactive session, I do not know how to switch between an interactive and non-interactive session.

I interpret this as "yes I am in an interactive session". As opposed to your code being run via cron job on a server. Or a Shiny app hosted somewhere. That sort of arms-length, non-interactive thing.

Are you working in an R Notebook or in an Rmd with the "Chunk output inline" behaviour selected? I'm trying to understand why gargle isn't leading you through the OAuth web flow and starting to cache tokens in the new cache location. I think your rlang version is new enough that this https://github.com/r-lib/gargle/issues/150 is not your problem, but just being safe.

So you're saying that in a completely fresh R session -- NO previous `.Rdata` being loaded, no `.Rprofile` attaching various stuff -- `drive_auth()` fails like this?

**Comment by claytonperry** [comment] 2021-04-20 16:21
Thank you for that explanation! The code is just being run in my RStudio on my local machine, not being hosted anywhere else (in a Shiny app or otherwise).

I'm not working in an R Notebook or an Rmd, I'm just working in a .R script that's saved locally to my machine (within a project with version control linked to a GitHub repository). My collaborators using the same script have not had any issue authorizing their connection to Google Drive using drive_auth(), I'm the only one running into this issue.

I just created a brand new R Project (which I believe should fulfill the conditions you mention in your last sentence) and ran the following code:

`library(googledrive)
options(gargle_verbosity  = 'debug')

drive_auth()`

and received the same error as before (in my initial comment in this issue). I'm very puzzled because as I mentioned I had no trouble with this until about one week ago.

**Comment by jennybc** [comment] 2021-04-20 16:46
I am guessing that gargle's new cache location is somehow the problem. But that the problem is somewhat unique to you. I will come back soon with some code for you to run.

**Comment by claytonperry** [comment] 2021-04-21 23:57
Thanks so much, Jenny! I'll keep an eye out for it.

**Comment by jennybc** [comment] 2021-04-29 18:13
Sorry, I haven't fired up my windows VM for a while. But I was there today. What do you see for this sort of code?

``` r
library(gargle)
library(fs)

(default_cache <- gargle:::gargle_default_oauth_cache_path())
#> C:/Users/jenny/AppData/Local/gargle/gargle/Cache

dir.exists(default_cache)
#> [1] TRUE

file_info(default_cache)[c("path", "permissions")]
#> # A tibble: 1 x 2
#>   path                                             permissions
#>   <fs::path>                                       <fs::perms>
#> 1 C:/Users/jenny/AppData/Local/gargle/gargle/Cache rw-

gargle_oauth_sitrep(default_cache)
#> 3 tokens found in this gargle OAuth cache:
#> 'C:/Users/jenny/AppData/Local/gargle/gargle/Cache'
#> 
#> email                   app            scopes          hash...   
#> _______________________ ______________ _______________ __________
#> jenny.f.bryan@gmail.com tidyverse-clio ...drive        403989c...
#> jenny.f.bryan@gmail.com gargle-clio                    5714de4...
#> jenny.f.bryan@gmail.com tidyverse-clio ...spreadsheets bb85656...

(legacy_cache <- gargle:::gargle_legacy_default_oauth_cache_path())
#> C:/Users/jenny/.R/gargle/gargle-oauth

dir.exists(legacy_cache)
#> [1] TRUE

file_info(legacy_cache)[c("path", "permissions")]
#> # A tibble: 1 x 2
#>   path                                  permissions
#>   <fs::path>                            <fs::perms>
#> 1 C:/Users/jenny/.R/gargle/gargle-oauth rw-

gargle_oauth_sitrep(legacy_cache)
#> 1 token found in this gargle OAuth cache:
#> 'C:/Users/jenny/.R/gargle/gargle-oauth'
#> 
#> email                   app            scopes   hash...   
#> _______________________ ______________ ________ __________
#> jenny.f.bryan@gmail.com tidyverse-clio ...drive 403989c...

sessioninfo::session_info("gargle")
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/Los_Angeles         
#>  date     2021-04-29                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package    * version    date       lib source                    
#>  askpass      1.1        2019-01-13 [1] CRAN (R 4.0.3)            
#>  cli          2.5.0.9000 2021-04-28 [1] Github (r-lib/cli@c9d103a)
#>  curl         4.3        2019-12-02 [1] CRAN (R 4.0.3)            
#>  fs         * 1.5.0      2020-07-31 [1] CRAN (R 4.0.3)            
#>  gargle     * 1.1.0.9000 2021-04-29 [1] local                     
#>  glue         1.4.2      2020-08-27 [1] CRAN (R 4.0.3)            
#>  httr         1.4.2      2020-07-20 [1] CRAN (R 4.0.3)            
#>  jsonlite     1.7.2      2020-12-09 [1] standard (@1.7.2)         
#>  mime         0.10       2021-02-13 [1] standard (@0.10)          
#>  openssl      1.4.3      2020-09-18 [1] CRAN (R 4.0.3)            
#>  R6           2.5.0      2020-10-28 [1] CRAN (R 4.0.3)            
#>  rappdirs     0.3.3      2021-01-31 [1] standard (@0.3.3)         
#>  rlang        0.4.10     2020-12-30 [1] standard (@0.4.10)        
#>  rstudioapi   0.13       2020-11-12 [1] CRAN (R 4.0.3)            
#>  sys          3.4        2020-07-23 [1] CRAN (R 4.0.3)            
#>  withr        2.4.2      2021-04-18 [1] standard (@2.4.2)         
#> 
#> [1] C:/Users/jenny/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.5/library
```

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by claytonperry** [comment] 2021-04-29 18:33
This proved instrumental! Thank you so much, Jenny! 

When I ran the first command I got:

```r
> (default_cache <- gargle:::gargle_default_oauth_cache_path())
C:/Users/perry/AppData/Local/gargle/gargle/Cache
> dir.exists(default_cache)
[1] FALSE
```
When I saw the FALSE output, instead of the TRUE output from your code, I went ahead and created the directory path referenced in the output from the first line of code. As soon as that path was created, I tried drive_auth() again and was directed to log into Google Drive like normal! I think this is resolved!! I can't thank you enough for the help!!

**Comment by jennybc** [comment] 2021-04-29 18:38
That's still pretty weird to me. This should get created automatically. Or rather, you should be asked it it's OK for us to create it. I'm going to leave this open for a bit in case anyone else sees similar and we can figure out why the "prompt + creation" isn't happening automagically.

**Comment by jennybc** [comment] 2021-05-25 23:41
Since no one else has shown up here, I'm going to close this and hope it's a weird one-off.

**Closed by jennybc** 2021-05-25 23:41 UTC
