### ISSUE TITLE
Unable to authorize from Rstudio Server

### ISSUE THREAD

**Issue by tiernanmartin** [tidyverse/googledrive#79] opened 2017-06-07 17:54 UTC
From Rstudio Server, I downloaded the package, ran `drive_search()`, and proceeding through the authorization process, which resulted in an error:

```
This site can't be reached; localhost refused to connect.
```
There's a nice [tutorial ](https://support.rstudio.com/hc/en-us/articles/217952868-Generating-OAuth-tokens-from-a-server) on how to overcome this problem by manually generating a token with the out of band option set to `TRUE`.

This worked for me:

```r
library(googledrive)
options(httr_oob_default=TRUE) 
drive_auth(new_user = TRUE) 

#> No token currently in force.
#>Please point your browser to the following url: 

#>  https://accounts.google.com/o/oauth2/...
```

It was not immediately obvious to me that the problem was related to the fact that I was running R in a server. Please consider adding this to the package's documentation to save future users the head scratching and googling.

Thanks for the great package - I'm looking forward to testing it out!

**Comment by LucyMcGowan** [comment] 2017-06-07 18:22
Thank you @tiernanmartin! We will get this documented - we are still *very* much working out the inner workings of this package, so there are a lot of pieces & use cases that are currently undocumented, but I appreciate you making a note of this so we remember to return to it.

**Comment by zacharytaojiang** [comment] 2018-06-08 23:20
yes, I also have this problem. I uploaded methylation data idat file to google drive. Then I used drive_get to get storage file. It can't work. “This site can't be reached; localhost refused to connect.” 
   Sorry, I am a new guy, crying now.

**Comment by jennybc** [comment] 2018-06-09 05:49
@zacharytaojiang What have you tried? Are you on RStudio Server? How does it unfold that you can upload the data (which would require) auth, but then you cannot get metadata on that just-uploaded file?

**Comment by florianm** [comment] 2018-09-19 09:59
Hi, I've got the same problem:

* RStudio Server (behind a Microsoft SSO and a corporate firewall) v 1.0.143
* googledrive master via `install_github()`
* R session info
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C               LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8    LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] wastdr_0.1.12          leaflet_2.0.2          sp_1.3-1               googledrive_0.1.1.9000 bindrcpp_0.2.2        
 [6] ckanr_0.1.2.9846       DBI_1.0.0              ggplot2_3.0.0          DT_0.4                 listviewer_1.4.0      
[11] lubridate_1.7.4        RColorBrewer_1.1-2     skimr_1.0.1            magrittr_1.5           tidyr_0.7.2           
[16] dplyr_0.7.6            here_0.1              

loaded via a namespace (and not attached):
 [1] httr_1.3.1            pkgload_1.0.0         jsonlite_1.5          shiny_1.1.0           assertthat_0.2.0     
 [6] highr_0.7             pander_0.6.1          yaml_2.2.0            lattice_0.20-35       pillar_1.3.0         
[11] backports_1.1.2       glue_1.3.0            digest_0.6.17         promises_1.0.1.9000   colorspace_1.3-2     
[16] htmltools_0.3.6       httpuv_1.4.5          plyr_1.8.4            pkgconfig_2.0.2       devtools_1.13.6.9000 
[21] purrr_0.2.5           xtable_1.8-3          scales_1.0.0          processx_3.2.0.9000   later_0.7.4.9000     
[26] git2r_0.23.0          tibble_1.4.2          openssl_1.0.2         usethis_1.3.0.9000    withr_2.1.2          
[31] lazyeval_0.2.1        cli_1.0.0.9002        crayon_1.3.4          mime_0.5              memoise_1.1.0        
[36] evaluate_0.11         ps_1.1.0              fs_1.2.3              pkgbuild_1.0.0        tools_3.4.4          
[41] stringr_1.3.1         munsell_0.5.0         callr_2.0.4.9000      compiler_3.4.4        rlang_0.2.2          
[46] debugme_1.1.0         grid_3.4.4            rstudioapi_0.7.0-9001 htmlwidgets_1.2       crosstalk_1.0.0      
[51] labeling_0.3          rmarkdown_1.10        testthat_2.0.0.9000   gtable_0.2.0          curl_3.2             
[56] R6_2.2.2              knitr_1.20            bindr_0.1.1           rprojroot_1.3-2       desc_1.2.0           
[61] stringi_1.2.4         Rcpp_0.12.18          dbplyr_1.2.0          tidyselect_0.2.4     
```

I'm getting the same error on any command of googledrive:
```
googledrive::drive_ls()
Error: length(url) == 1 is not TRUE
```

Gut feeling: auth tries to open a "localhost" browser tab, which gets stuck between our firewall, the reverse proxy and Google OAuth. The constructed URL seems to include a missing or empty port and therefore is not one, but two strings.

Positive example: googledrive authentication works fine from RStudio Desktop, opening a Google OAuth permissions browser tab, then confirming with the "localhost" tab.

What specifically can I test from my end to provide more debug info?

**Comment by jennybc** [comment] 2018-09-19 15:29
@florianm Have you tried the explicit `drive_auth()` workflow at the very top that forces out of band auth? That can actually be simplified (the call to options should be removed), as you can set `use_oob` inside the `drive_auth()` call.

**Comment by florianm** [comment] 2018-09-20 03:14
@jennybc thanks, that was it.

Here's how to break and fix auth in RStudio Server:

```
> googledrive::drive_auth(reset=TRUE, use_oob=FALSE)
Disabling .httr-oauth by renaming to .httr-oauth-SUSPENDED
Removing google token stashed internally in 'googledrive'.
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```
This tries to open a tab to `http://localhost:1410/?state=STATE&code=CODE`. This of course can't work from RStudio Server running on a separate domain, such as https://rstudio.mycompany.com/. 
The localhost URL actually contains the CODE we need to paste into R's console to complete the authorisation, but R won't show the prompt until the tab manages to load.

Important note: The code below won't work until the R session has been restarted!

```
> googledrive::drive_auth(reset=TRUE, use_oob = TRUE)
Disabling .httr-oauth by renaming to .httr-oauth-SUSPENDED
No token currently in force.
Use a local file ('.httr-oauth'), to cache OAuth access credentials between R sessions?

1: Yes
2: No

Selection: 1
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```
Tab opens, click "Sign in", "Allow", opens new tab like `https://accounts.google.com/o/oauth2/approval/v2/approvalnativeapp?auto=false&response=GARBLE&hl=en&approvalCode=CODE`.
Once the page has loaded, R shows the prompt to paste the approval code.
``` 
Enter authorization code:
```
This creates a local `.httr-oauth` file, and subsequent googledrive commands work.

Thanks for the quick help, @jennybc !

**Comment by jennybc** [comment] 2018-09-20 04:44
We obviously need to make this less difficult and obscure. Thanks for trying it out.

**Comment by jennybc** [comment] 2018-12-16 07:08
If you need to authorize for use on a server, a service account token is probably preferable to an OAuth token in any case. That is what googledrive itself does on, for example, travis and appveyor.

Here's where it's done:
https://github.com/tidyverse/googledrive/blob/28fdf0c96a8c5a6d5c1dbaf65f4751d87a03118d/tests/testthat/helper.R#L19-L20

Like an OAuth token, the JSON file containing the service account token should be treated like a password, i.e. kept securely. In our travis and appveyor workflows, it is kept as an encrypted file and decrypted at build & test time. But a service account token is easier to get as a simple file and to place on a server.

**Comment by Zedseayou** [comment] 2019-03-23 22:04
In case it's relevant to anyone who searches for this and happens to be on an older version of `googledrive` (in my case the setup was on 0.1.2.9000), the relevant option there was `options(gargle.oob_default=TRUE)` which I hadn't seen mentioned elsewhere

**Comment by xinyihou** [comment] 2019-03-26 00:22
I also have a bug about authorizing google drive from R Studio Server. When I call `googledrive::grive_auth(service_token = 'secret.json')`, my RStudio server would crash or wait forever, like 
<img width="379" alt="Screen Shot 2019-03-25 at 5 18 52 PM" src="https://user-images.githubusercontent.com/18456309/54962566-95aaec80-4f22-11e9-825a-74b00f8b8dd1.png">

**Comment by jennybc** [comment] 2019-03-27 16:07
I think dev googledrive is out of sync with dev gargle at the moment. I will fix that later today!

**Comment by xinyihou** [comment] 2019-03-27 17:11
I just installed the gargle package and the problem is resolved. Thanks, Jenny!

**Comment by r4zZ-90** [comment] 2019-06-10 11:41
Those authenfication workarounds worked for me. Thanks for the great package and everyone who helped!

But I ran into another issue: on my R Server I couldnt download files, but with same code had no issue on my desktop version.

Error on R Server is: 
"Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Failed to open file accounting API sheet.csv."

Anyone has an idea what the issue could be?

**Comment by jennybc** [comment] 2019-06-11 05:11
Is there any chance you're trying to write to a path where you don't have permission? Can you do other auth-requiring things via googledrive that only effect Drive and not the local filesystem?

**Comment by jennybc** [comment] 2019-08-14 17:03
I plan to surface docs/examples from recent successful experiments with RStudio Server and Connect and close this.

**Comment by jennybc** [comment] 2019-08-16 02:05
Hello People of Issue 79,

I come in peace.

I think this is now reasonably well documented for the impending googledrive release, which uses gargle for auth:

https://gargle.r-lib.org/articles/auth-from-web.html

In any case, doing and explaining this is now a job for gargle. So I'm closing this issue.

If you have feedback on that vignette, please put it here:

https://github.com/r-lib/gargle/issues/105

**Closed by jennybc** 2019-08-16 02:05 UTC
Labels: documentation

**Comment by getVishalSingh** [comment] 2020-01-17 01:56
Hi,
I am using R in google colab. I tried the way it's explained in **https://gargle.r-lib.org/articles/auth-from-web.html**. However, it fails in authentication and redirects to localhost:1410. Looking for some help.

**Comment by jennybc** [comment] 2020-01-17 03:45
I'm afraid I must refer you to #284 (which is not yet resolved) @getVishalSingh

**Comment by os2137** [comment] 2020-05-04 09:05
This worked for me finally for authorization: 
library(googledrive)
options(httr_oob_default=TRUE) 
drive_auth()
