### ISSUE TITLE
drive_mkdir() freezes

### ISSUE THREAD

**Issue by mehrnoushmalek** [tidyverse/googledrive#317] opened 2020-08-11 19:06 UTC
Hi,

I'm using R 4.0.2, and I was trying to create a folder on my Drive, but it freezes, and nothing happens. 
Authentication seems to be  successful (drive_user shows the email and name), and `drive_find` showed the folders. I would appreciate it if you can let me know what the issue is, or what I'm doing wrong.

Thanks,

**Comment by jennybc** [comment] 2020-08-11 19:14
Works for me. Without more information, i.e. a reprex, I have nothing to go on.

``` r
library(googledrive)
```

``` r
ghi <- drive_mkdir("ghi")
#> Auto-refreshing stale OAuth token.
#> Created Drive file:
#>   * ghi: 1TbJX0V9sFmtlngp6TJ53sscXLwOg_PhK
#> with MIME type:
#>   * application/vnd.google-apps.folder

# cleanup
drive_rm(ghi)
#> Files deleted:
#>   * ghi: 1TbJX0V9sFmtlngp6TJ53sscXLwOg_PhK
```

<sup>Created on 2020-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mehrnoushmalek** [comment] 2020-08-11 19:21
Thanks for the response. I know that it works, as it worked for my colleague, but I'd like to know why it may not work in some cases. You have R version >=4.0.2?

**Comment by jennybc** [comment] 2020-08-11 20:42
As the error indicates, it appears to be on server i.e. Google side. That's true, in general, of errors >= 500. So I'm afraid I don't know what to suggest. There's nothing to go on here in terms of something you or googledrive could do differently. But it's also likely to self-resolve and we'll never really know what was up.

**Comment by jennybc** [comment] 2020-08-11 20:46
And yes I'm on 4.0.2.

``` r
R.version.string
#> [1] "R version 4.0.2 (2020-06-22)"
```

<sup>Created on 2020-08-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by mehrnoushmalek** [comment] 2020-08-11 21:12
It's strange. I tried another google account, and did the exact same steps, and it worked. Now I'm curious to know where my servers are!

**Comment by jennybc** [comment] 2020-08-12 00:40
I'm going to close this. I don't deny what you've experienced but I also think there's nothing googledrive can do.

**Closed by jennybc** 2020-08-12 00:40 UTC

**Comment by py9mrg** [comment] 2020-12-15 15:36
I think I'm experiencing the same issue, but it seems a little more persistent and a little more wide ranging for me so I thought I'd add a comment. Essentially, it seems that anything using `drive_find` works ok, either using `pattern = "name"` or `q = "name contains 'name'"` style use. But nearly all the `drive_*` functions are problematic for me - especially ones that seem to work with folders rather than files (although `drive_find(pattern = "name", type = "folder")` will work fine). But `drive_mkdir()` or anything like that won't.

I think it's something to do with path/folder issues. The reason I suspect this is that I have real problems with `drive_ls()` too. For example, in the documentation:

```
# search for files located directly in your root folder
drive_find(q = "'root' in parents")
# FYI: this is equivalent to
drive_ls("~/")
```

The former will work fine for me, but the latter just hangs. In fact, if I try and do anything path style it just doesn't seem to work with any functions, e.g.: `drive_ls(path = "abc", pattern = "def")` will hang, while `drive_get(id = "root")` will work but `drive_get("abc")` or `drive_get("def/")` won't.

Similarly for any of the `drive_mv/cp/mkdir` functions, they just hang whether working on folders or individual files - the `drive_cp` documentation, for example, will hang on even the first line: `file <- drive_upload(drive_example("chicken.txt"), "chicken-cp.txt")`.

It's very strange and with no error messages unless I whack Esc twice then I'm lost as to the cause. If there's any tests / reprexes I can do to help then let me know.
