### ISSUE TITLE
drive_ls output is wrong

### ISSUE THREAD

**Issue by spocks** [tidyverse/googledrive#303] opened 2020-04-03 15:28 UTC
`drive_ls` (and `drive_find`) is returning variable and wrong number of files on each call. 
I am using _googledrive_1.0.0.9000_
```r
> packageVersion("googledrive")
[1] ‘1.0.0.9000’

> lst1 = drive_ls(mydir)
Items so far: 
200 248 
> print(dim(lst1))
[1] 248   3
> lst2 = drive_ls(mydir)
Items so far: 
100 
> print(dim(lst2))
[1] 100   3
> 
```

**Comment by jennybc** [comment] 2020-04-03 17:32
Duplicate of #288, which AFAICT is a bug (or at least behaviour) of the Drive API that I have no control over. If you can glean any insight into the files that appear in one call to `drive_ls()` but not another, I'm very interested and you could add to #288. Are they ... very old? very new? owned by someone else?

**Closed by jennybc** 2020-04-03 17:32 UTC
