### ISSUE TITLE
drive_ls() returns different number of files every call (large folder)

### ISSUE THREAD

**Issue by keuapar** [tidyverse/googledrive#391] opened 2022-03-23 20:05 UTC
Hi, I have a large folder (with 900 files), and I need their list. Running drive_ls() returns a different number of files on each successive call, usually a multiple of 100. On my friend's laptop, it gave all 900 files at once, and another time 896 files. I have no clue why this is happening... Finally after several attempts I got 900, but I don't want to rely on checking this manually. Any advice appreciated!

![image](https://user-images.githubusercontent.com/17890695/159786263-c88c538e-0b2d-4d76-a79b-c26a25a9aa95.png)

**Comment by jennybc** [comment] 2022-03-27 00:44
Duplicate of #303, #288, etc.

**Closed by jennybc** 2022-03-27 00:44 UTC
