### ISSUE TITLE
Revoke Anyone With Link Permission.

### ISSUE THREAD

**Issue by marcofaga** [tidyverse/googledrive#445] opened 2023-09-06 17:53 UTC
Hi. How can I revoke the "anyone with link" permission for a file? I would like to restrict access to the file only to the owner.

I´ve tried 

`drive_share(file = ap_id,
                       role = "reader",
                       type = "user",
                       emailAddress = "sasa@asa.com")`

but it didn´t work :-(

**Comment by jennybc** [comment] 2023-09-15 18:36
I think this is basically a duplicate of #392 and #180. I have started the work to address that in #394 but it's incomplete. So, as it stands, googledrive does not have the ability to revoke that permission 😢

**Closed by jennybc** 2023-09-15 18:36 UTC
